apiVersion: v1
kind: Service
metadata:
  name: ms-talks
spec:
  selector:
    app: ms-talks
  ports:
    - protocol: "TCP"
      port: 80
      targetPort: 8080
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-talks
spec:
  selector:
    matchLabels:
      app: ms-talks
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-talks
    spec:
      containers:
        - name: ms-talks
          image: registry.dev.redbee.io/conf/ms-talks:0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-talks-postgresql.redbee-conf.svc.cluster.local:5432/postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-talks-postgresql
                  key: postgresql-password
            - name: SERVER_PORT
              value: "8080"
      imagePullSecrets:
        - name: regcred