spring:
  application:
    name: ms-conferences
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: password

server:
  port: 3001
  error:
    include-message: always

