
name: ms-conferences -> build, test, & deploy

on:
  pull_request:
    paths:
      - ms-conferences/**
  push:
    paths:
      - ms-conferences/**
    branches:
      - master
      
defaults:
  run:
    working-directory: ./ms-conferences

jobs:
  # JOB to build and test backend code
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          # settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: gradle build
  
  deploy:
    if: ${{ github.event_name != 'pull_request' && github.event_name != 'pull_request_target' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: registry.dev.redbee.io/conf/ms-conferences:${{ github.sha }}
        env:
          GIT_AUTH_TOKEN: ${{ secrets.DOCKER_REGISTRY_AUTH }}
      
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/ms-conferences container=registry.dev.redbee.io/conf/ms-conferences:${{ github.sha }}
