
name: ms-conferences

on:
  pull_request:
    paths:
      - ms-conferences/**
  push:
    paths:
      - ms-conferences/**
    branches:
      - master
      
defaults:
  run:
    working-directory: ./ms-conferences

jobs:
  # JOB to build and test backend code
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          # server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          # settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Build with Gradle
        run: gradle build

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/ms-conferences/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 20
          min-coverage-changed-files: 50

#    if: ${{ github.event_name != 'pull_request' && github.event_name != 'pull_request_target' }}
      - uses: actions/checkout@v2
      - name: docker build and push
        id: docker_build
        env:
          DOCKER_CONFIG: ${{ secrets.DOCKER_REGISTRY_AUTH }}
        run: |
          echo "$DOCKER_CONFIG" | base64 -d > config.json
          docker build -t registry.dev.redbee.io/conf/ms-conferences .
          docker tag registry.dev.redbee.io/conf/ms-conferences:latest registry.dev.redbee.io/conf/ms-conferences:${{ github.sha }}
          docker --config="$PWD" push registry.dev.redbee.io/conf/ms-conferences:${{ github.sha }}
      
      - name: deploy to cluster
        uses: steebchen/kubectl@v2.0.0
        with: # defaults to latest kubectl binary version
          config: ${{ secrets.KUBE_CONFIG_DATA }}
          command: set image --record deployment/ms-conferences container=registry.dev.redbee.io/conf/ms-conferences:${{ github.sha }}
