
name: ms-talks

on:
  pull_request:
    paths:
      - ms-talks/**
  push:
    paths:
      - ms-talks/**
    branches:
      - master
      
defaults:
  run:
    working-directory: ./ms-talks

jobs:
  # JOB to build and test backend code
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build with Gradle
        run: gradle build

      - uses: actions/upload-artifact@master
        with:
          name: ms-talks-jar
          path: ms-talks/build/libs/

      - if: ${{ github.event_name == 'pull_request' || github.event_name == 'pull_request_target' }}
        name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.2
        with:
          paths: ${{ github.workspace }}/ms-talks/build/reports/jacoco/test/jacocoTestReport.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 20
          min-coverage-changed-files: 50

  deploy:
    if: ${{ github.event_name != 'pull_request' && github.event_name != 'pull_request_target' }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@master
        with:
          name: ms-talks-jar
          path: ms-talks/build/libs/

      - name: docker build and push
        id: docker_build
        env:
          DOCKER_CONFIG: ${{ secrets.DOCKER_REGISTRY_AUTH }}
        run: |
          echo "$DOCKER_CONFIG" | base64 -d > config.json
          docker build -t registry.dev.redbee.io/conf/ms-talks .
          docker tag registry.dev.redbee.io/conf/ms-talks:latest registry.dev.redbee.io/conf/ms-talks:${{ github.sha }}
          docker --config="$PWD" push registry.dev.redbee.io/conf/ms-talks:${{ github.sha }}
      
      - name: deploy to cluster
        uses: actions-hub/kubectl@master
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG_DATA }}
        with: # defaults to latest kubectl binary version
          args: set image deployment/ms-talks ms-talks=registry.dev.redbee.io/conf/ms-talks:${{ github.sha }} -n redbee-conf
