name: web-app-conf

on:
#  pull_request:
#    paths:
#      - ms-talks/**
  push:
    paths:
      - web-app-conf/**
    branches:
      - master

defaults:
  run:
    working-directory: ./web-app-conf

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_SECRET }}
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm i

      - name: Build
        run: npm run build

      - name: Deploy
        uses: reggionick/s3-deploy@v3
        with:
          folder: web-app-conf/build
          bucket: ${{ secrets.S3_BUCKET }}
          bucket-region: ${{ secrets.S3_BUCKET_REGION }}